media:
  input: public
  output: /
content:
  - name: life
    label: Life
    type: collection
    path: src/content/life
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: subTitle, label: Sub Title, type: string }
      - { name: pubDate, label: Publish Date, type: date, required: true }
      - { name: updatedDate, label: Updated Date, type: date }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: level, label: Level, type: number }
      - { name: top, label: Top, type: number }
      - { name: description, label: Description, type: string }
      - { name: body, label: Body, type: rich-text }